#!/bin/bash

echo "<schema-name>"
/usr/local/bin/aws athena start-query-execution \
--query-string "ALTER TABLE <schema-name> ADD PARTITION(year='$year',month='$month',day='$day') location 's3://<s3-source-bucket>/$year/$month/$day/'" \
--query-execution-context Database=<database-name> \
--result-configuration OutputLocation=s3://<s3-log-bucket>

exit
